### ISSUE TITLE
Spell option cannot be disabled for carbon buffer via after/ftplugin/carbon.lua file

### ISSUE THREAD

**Issue by datwaft** [SidOfc/carbon.nvim#13] opened 2022-03-11 04:18 UTC
After setting `set spell` on my init.lua I cannot disable it only for carbon buffer using `after/ftplugin/carbon.lua`.

I have tested that the file is run by printing inside the file, but it seems that spell is not disabled.

![image](https://user-images.githubusercontent.com/37723586/157801098-fbbed0a7-a247-4caf-90bf-1817983be1a1.png)

I created an small reproduction repository [here](https://github.com/datwaft/carbon.nvim_spell_issue).

**Comment by SidOfc** [comment] 2022-03-11 18:06
Hello @datwaft!

Cheers for the report, the issue has been patched in my last commit. Every time a Carbon buffer is shown the `spell` option will be disabled. You can still manually enable it afterwards with `:set spell`.

I implemented this patch mainly because I think this is a sane default. When I recreated the setup locally in my development environment I did not even succeed in getting the file to print anything though.

Given the following structure (content of `after/ftplugin/carbon.lua` on the left):

<img width="947" alt="image" src="https://user-images.githubusercontent.com/3225058/157923534-ff067484-f0be-44ce-9e1b-7c0e5babf221.png">

The output of running `:script` right after startup was:

<img width="950" alt="image" src="https://user-images.githubusercontent.com/3225058/157923692-cb64679f-d37b-4453-b272-8fbebf285c0f.png">

I'm not sure why the file isn't loaded but I don't think Carbon is "the cause" of the issue because the plugin itself does not control which files/folders Neovim decides to load. Because of this I will close this issue, feel free to correct me if I'm wrong of course!

Thanks again for the report, at the very least it added a sane default to Carbon 👍

**Closed by SidOfc** 2022-03-11 18:06 UTC
Labels: improvement
