### ISSUE TITLE
Restoring a session containing a carbon sidebar breaks carbon

### ISSUE THREAD

**Issue by dhazel** [SidOfc/carbon.nvim#121] opened 2023-02-09 18:01 UTC
Thanks for the great plugin! 

Neovim version: 0.8.2
OS: Windows 10

Steps to reproduce:
1. Open neovim
2. Open the carbon sidebar, `:ToggleSidebarCarbon`
3. Save the session, `:mksession mysession.vim`
4. Close neovim
5. Open neovim
6. Restore the session, `:source mysession.vim`
7. Observe that the sidebar is created but carbon does not render in the sidebar
8. Attempt to toggle the carbon sidebar, `:ToggleSidebarCarbon`
9. Observe that carbon does not render and an error is thrown in messages:

````
Error executing Lua callback: ...ata/Local/nvim-data/lazy/carbon.nvim/lua/carbon/util.lua:195: Vim:E95: Buffer with this name already exists
stack traceback:
	[C]: in function 'nvim_buf_set_name'
	...ata/Local/nvim-data/lazy/carbon.nvim/lua/carbon/util.lua:195: in function 'create_scratch_buf'
	...a/Local/nvim-data/lazy/carbon.nvim/lua/carbon/buffer.lua:54: in function 'handle'
	...a/Local/nvim-data/lazy/carbon.nvim/lua/carbon/buffer.lua:99: in function 'show'
	.../AppData/Local/nvim-data/lazy/carbon.nvim/lua/carbon.lua:224: in function 'explore_sidebar'
	.../AppData/Local/nvim-data/lazy/carbon.nvim/lua/carbon.lua:198: in function <.../AppData/Local/nvim-data/lazy/carbon.nvim/lua/carbon.lua:185>
Failed to run `config` for carbon.nvim

...ata/Local/nvim-data/lazy/carbon.nvim/lua/carbon/util.lua:195: Failed to rename buffer

# stacktrace:
  - carbon.nvim\lua\carbon\util.lua:195 _in_ **create_scratch_buf**
  - carbon.nvim\lua\carbon\buffer.lua:54 _in_ **handle**
  - carbon.nvim\lua\carbon\buffer.lua:99 _in_ **show**
  - carbon.nvim\lua\carbon\buffer.lua:22 _in_ **launch**
  - carbon.nvim\lua\carbon.lua:87 _in_ **initialize**
  - carbon.nvim\lua\carbon.lua:29 _in_ **setup**
E492: Not an editor command: qw
````

**Comment by SidOfc** [comment] 2023-02-11 17:03
Hello again @dhazel, partial support for restoring sessions has been implemented. It works to the point where Carbon will show the buffer and can identify that it was a sidebar pane however there are certain parts which would be tricky to support and/or store in vim sessions, such as traversed and/or currently open directories.

I am not planning to implement full-blown session support at this time however as time passes and more complex use-cases pop up I will certainly take sessions into consideration during refactors as it seems like it would be really neat to have good integration at some point :)

Anyways, you should be able to update to latest stable after which you can at least restore sessions with Carbon in a _somewhat_ reasonable/workable state, and the `ToggleSidebarCarbon` command should also no longer crash.

I will close this issue since I tested this myself and confirmed that it works at least on my machine (famous last words hehe). Of course if you do find something I mentioned above does not work as described feel free to add a comment in this issue.

Thanks again for the report, have a good one 👍

**Closed by SidOfc** 2023-02-11 17:03 UTC
Labels: bug
